development:
  adapter: postgresql
  encoding: utf8
  database: imenu_development
  pool: 5
  username: lucas03
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: imenu_test
  pool: 5
  username: lucas03
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: imenu_production
  pool: 5
  username: lucas03
  password:
